"""
대화 주제 뱅크.
- TOPIC_BANK: 내장 주제 (API 비용 없이 매일 결정적으로 6개 로테이션)
- SCENARIOS: 롤플레이 시나리오 (AI 역할 + 상황)
- 개인화 추천은 openai_service.generate_personal_topics 로 사용자의 키를 써서 만든다 (하루 1회 캐시).
"""

import hashlib
from datetime import datetime, timedelta, timezone

KST = timezone(timedelta(hours=9))


def today_kst() -> str:
    return datetime.now(KST).strftime("%Y-%m-%d")


# (id, emoji, category, title_en, title_ko, description_ko, starter questions)
_RAW = [
    (
        "morning-routine",
        "☀️",
        "daily",
        "Your morning routine",
        "아침 루틴",
        "일어나서 집을 나서기까지의 습관을 설명해 보세요.",
        [
            "What time do you usually wake up?",
            "What's the first thing you do?",
            "Are you a morning person?",
        ],
    ),
    (
        "weekend-plans",
        "🗓️",
        "daily",
        "Weekend plans",
        "주말 계획",
        "이번 주말에 하고 싶은 일과 지난 주말 이야기.",
        [
            "Any plans for the weekend?",
            "What did you do last weekend?",
            "Do you prefer busy or lazy weekends?",
        ],
    ),
    (
        "favorite-food",
        "🍜",
        "food",
        "Comfort food",
        "위로가 되는 음식",
        "힘들 때 찾게 되는 음식과 그 이유.",
        [
            "What's your go-to comfort food?",
            "Can you cook it yourself?",
            "What food reminds you of home?",
        ],
    ),
    (
        "cooking",
        "🍳",
        "food",
        "Cooking at home vs eating out",
        "집밥 vs 외식",
        "요리 습관과 외식 문화 비교.",
        [
            "How often do you cook?",
            "What's the last thing you cooked?",
            "Is eating out expensive where you live?",
        ],
    ),
    (
        "coffee",
        "☕",
        "food",
        "Coffee culture",
        "카페와 커피 문화",
        "커피 취향, 카페 문화, 카페에서 일하기.",
        [
            "Coffee or tea?",
            "Do you have a favorite cafe?",
            "Why do you think cafes are so popular in Korea?",
        ],
    ),
    (
        "travel-memory",
        "✈️",
        "travel",
        "A trip you'll never forget",
        "잊지 못할 여행",
        "가장 기억에 남는 여행 경험을 이야기해 보세요.",
        [
            "Where was the best trip you've taken?",
            "What made it special?",
            "Did anything go wrong?",
        ],
    ),
    (
        "dream-destination",
        "🗺️",
        "travel",
        "Dream destination",
        "꿈의 여행지",
        "가보고 싶은 나라와 그곳에서 하고 싶은 것.",
        [
            "If you could go anywhere tomorrow, where?",
            "Beach or mountains?",
            "Do you plan trips carefully or go with the flow?",
        ],
    ),
    (
        "solo-travel",
        "🎒",
        "travel",
        "Solo travel",
        "혼자 여행하기",
        "혼자 여행의 장단점과 경험.",
        [
            "Have you ever traveled alone?",
            "What are the pros and cons?",
            "How do you meet people when traveling?",
        ],
    ),
    (
        "hobbies",
        "🎨",
        "life",
        "Hobbies and free time",
        "취미와 여가",
        "요즘 빠져 있는 것과 시작하고 싶은 취미.",
        [
            "What do you do to relax?",
            "Have you picked up any new hobbies recently?",
            "What hobby would you like to try?",
        ],
    ),
    (
        "exercise",
        "🏃",
        "health",
        "Staying active",
        "운동과 건강 관리",
        "운동 습관, 헬스장, 러닝, 동기부여.",
        ["Do you exercise regularly?", "What keeps you motivated?", "Gym or outdoors?"],
    ),
    (
        "sleep",
        "😴",
        "health",
        "Sleep habits",
        "수면 습관",
        "잠, 불면, 낮잠, 숙면 팁.",
        [
            "Are you a good sleeper?",
            "How many hours do you need?",
            "Any tips for better sleep?",
        ],
    ),
    (
        "stress",
        "🧘",
        "health",
        "Dealing with stress",
        "스트레스 관리",
        "스트레스의 원인과 나만의 해소법.",
        [
            "What stresses you out most these days?",
            "How do you deal with it?",
            "Does talking to friends help?",
        ],
    ),
    (
        "work-life",
        "⚖️",
        "work",
        "Work-life balance",
        "워라밸",
        "일과 삶의 균형, 야근 문화, 이상적인 근무 방식.",
        [
            "Is work-life balance good in your job?",
            "Would you take a pay cut for more free time?",
            "What does an ideal workday look like?",
        ],
    ),
    (
        "remote-work",
        "🏠",
        "work",
        "Working from home",
        "재택근무",
        "재택근무 경험과 장단점.",
        [
            "Have you worked from home?",
            "Do you get more done at home or in the office?",
            "How do you stay focused?",
        ],
    ),
    (
        "career-goals",
        "🚀",
        "work",
        "Career goals",
        "커리어 목표",
        "5년 뒤 목표와 지금 준비하는 것.",
        [
            "Where do you see yourself in five years?",
            "What skills are you building?",
            "What would your dream job be?",
        ],
    ),
    (
        "first-job",
        "👔",
        "work",
        "Your first job",
        "첫 직장 / 첫 아르바이트",
        "첫 일 경험에서 배운 것.",
        [
            "What was your first job?",
            "What did you learn from it?",
            "Was your boss nice?",
        ],
    ),
    (
        "studying",
        "📚",
        "study",
        "How you study",
        "공부 방법",
        "효과적인 공부법, 집중력, 미루기.",
        ["How do you usually study?", "Are you a procrastinator?", "Library or cafe?"],
    ),
    (
        "learning-english",
        "🗣️",
        "study",
        "Learning English",
        "영어 공부 이야기",
        "영어를 배우는 이유와 어려운 점.",
        [
            "Why are you learning English?",
            "What's the hardest part for you?",
            "How do you practice speaking?",
        ],
    ),
    (
        "school-memories",
        "🏫",
        "study",
        "School memories",
        "학창 시절",
        "학교 다닐 때 기억에 남는 일.",
        [
            "What kind of student were you?",
            "Who was your favorite teacher?",
            "Any funny school memories?",
        ],
    ),
    (
        "movies",
        "🎬",
        "culture",
        "Movies and series",
        "영화와 드라마",
        "최근 본 작품과 취향.",
        [
            "What have you watched recently?",
            "Do you rewatch things?",
            "Cinema or streaming at home?",
        ],
    ),
    (
        "music",
        "🎧",
        "culture",
        "Music taste",
        "음악 취향",
        "좋아하는 장르, 콘서트 경험, 플레이리스트.",
        [
            "What are you listening to these days?",
            "Have you been to a concert?",
            "Does music help you focus?",
        ],
    ),
    (
        "books",
        "📖",
        "culture",
        "Books and reading",
        "책과 독서",
        "최근 읽은 책과 독서 습관.",
        [
            "Do you read much?",
            "Paper or e-books?",
            "What book would you recommend to me?",
        ],
    ),
    (
        "kpop-culture",
        "🎤",
        "culture",
        "Korean culture abroad",
        "해외에서의 한국 문화",
        "K-pop, K-드라마, 한식이 인기 있는 이유.",
        [
            "Why do you think K-culture became so popular?",
            "What Korean thing should I try first?",
            "Has it changed how foreigners see Korea?",
        ],
    ),
    (
        "social-media",
        "📱",
        "tech",
        "Social media",
        "소셜 미디어",
        "SNS 사용 습관과 영향.",
        [
            "Which apps do you use most?",
            "Have you tried a digital detox?",
            "Is social media good or bad for us?",
        ],
    ),
    (
        "ai-future",
        "🤖",
        "tech",
        "AI and the future of work",
        "AI와 일의 미래",
        "AI가 바꿀 직업과 우리의 대응.",
        [
            "Do you use AI tools?",
            "Which jobs will change the most?",
            "Are you excited or worried?",
        ],
    ),
    (
        "smartphone",
        "📲",
        "tech",
        "Life without a smartphone",
        "스마트폰 없는 하루",
        "스마트폰 의존과 없이 살기.",
        [
            "How long could you go without your phone?",
            "What's the most useful app?",
            "Do you feel addicted?",
        ],
    ),
    (
        "gaming",
        "🎮",
        "tech",
        "Video games",
        "게임",
        "게임 취향과 게임 문화.",
        ["Do you play games?", "Mobile or PC?", "Are games a waste of time?"],
    ),
    (
        "city-vs-country",
        "🌆",
        "society",
        "City vs countryside",
        "도시 vs 시골",
        "어디서 살고 싶은지와 이유.",
        [
            "Would you rather live in a city or the countryside?",
            "What do you like about where you live?",
            "Where would you retire?",
        ],
    ),
    (
        "housing",
        "🏡",
        "society",
        "Housing and rent",
        "집과 월세",
        "자취, 집값, 이상적인 집.",
        [
            "Do you live alone or with family?",
            "Is rent expensive in your city?",
            "Describe your dream home.",
        ],
    ),
    (
        "public-transport",
        "🚇",
        "society",
        "Getting around",
        "교통과 통근",
        "통근 방법, 지하철, 운전.",
        [
            "How do you get to work or school?",
            "Do you enjoy driving?",
            "What's the public transport like?",
        ],
    ),
    (
        "environment",
        "🌱",
        "society",
        "Small green habits",
        "환경을 위한 작은 습관",
        "재활용, 텀블러, 기후 변화.",
        [
            "Do you recycle?",
            "What small habits could help the planet?",
            "Do you worry about climate change?",
        ],
    ),
    (
        "money",
        "💸",
        "life",
        "Saving and spending",
        "소비와 저축",
        "돈 관리 습관, 최근 산 물건.",
        [
            "Are you a saver or a spender?",
            "What was your last big purchase?",
            "Any money-saving tips?",
        ],
    ),
    (
        "shopping",
        "🛍️",
        "life",
        "Shopping habits",
        "쇼핑 습관",
        "온라인 쇼핑, 충동구매, 반품.",
        [
            "Online or in-store?",
            "Do you make impulse purchases?",
            "What do you refuse to spend money on?",
        ],
    ),
    (
        "pets",
        "🐶",
        "life",
        "Pets",
        "반려동물",
        "반려동물 경험과 키우고 싶은 동물.",
        [
            "Do you have a pet?",
            "Cats or dogs?",
            "What's the hardest part of having a pet?",
        ],
    ),
    (
        "family",
        "👨‍👩‍👧",
        "life",
        "Family",
        "가족 이야기",
        "가족 구성과 가족과 보내는 시간.",
        [
            "Tell me about your family.",
            "Who are you closest to?",
            "How often do you see them?",
        ],
    ),
    (
        "friendship",
        "🤝",
        "life",
        "Friendship",
        "우정",
        "오랜 친구와 새 친구 사귀기.",
        [
            "How did you meet your best friend?",
            "Is it hard to make friends as an adult?",
            "What makes a good friend?",
        ],
    ),
    (
        "childhood",
        "🧸",
        "life",
        "Childhood memories",
        "어린 시절",
        "어릴 적 기억, 놀이, 꿈.",
        [
            "What did you want to be as a kid?",
            "What games did you play?",
            "What's your earliest memory?",
        ],
    ),
    (
        "seasons",
        "🍂",
        "daily",
        "Seasons and weather",
        "계절과 날씨",
        "좋아하는 계절과 날씨에 따른 기분.",
        [
            "What's your favorite season?",
            "Does weather affect your mood?",
            "How's the weather today?",
        ],
    ),
    (
        "holidays",
        "🎄",
        "culture",
        "Holidays and traditions",
        "명절과 전통",
        "설날, 추석, 크리스마스 보내는 법.",
        [
            "How do you celebrate the biggest holiday in Korea?",
            "Do you enjoy family gatherings?",
            "What holiday food do you love?",
        ],
    ),
    (
        "birthday",
        "🎂",
        "life",
        "Birthdays",
        "생일",
        "생일을 보내는 방식과 선물.",
        [
            "How do you usually spend your birthday?",
            "What's the best gift you've received?",
            "Do you like surprises?",
        ],
    ),
    (
        "fashion",
        "👟",
        "life",
        "Personal style",
        "패션과 스타일",
        "옷 취향과 쇼핑.",
        [
            "How would you describe your style?",
            "Do you follow trends?",
            "What do you wear to feel confident?",
        ],
    ),
    (
        "photography",
        "📷",
        "culture",
        "Taking photos",
        "사진 찍기",
        "사진 취미, 폰 카메라, 인생샷.",
        [
            "Do you take many photos?",
            "What do you like to photograph?",
            "Do you print photos?",
        ],
    ),
    (
        "news",
        "📰",
        "society",
        "Following the news",
        "뉴스와 정보",
        "뉴스 소비 습관, 가짜 뉴스.",
        [
            "How do you get your news?",
            "Do you trust the news?",
            "Is it healthy to follow news all day?",
        ],
    ),
    (
        "languages",
        "🌍",
        "study",
        "Learning languages",
        "외국어 배우기",
        "배우고 싶은 언어와 방법.",
        [
            "What other languages would you learn?",
            "Is Korean hard for foreigners?",
            "Apps or classes?",
        ],
    ),
    (
        "happiness",
        "😄",
        "deep",
        "What makes you happy",
        "행복",
        "소소한 행복과 삶의 의미.",
        [
            "What made you smile this week?",
            "What does happiness mean to you?",
            "Money and happiness—related?",
        ],
    ),
    (
        "regrets",
        "🪞",
        "deep",
        "Lessons and regrets",
        "후회와 배움",
        "과거의 선택과 배운 교훈.",
        [
            "Do you have any regrets?",
            "What advice would you give your younger self?",
            "Do mistakes help us grow?",
        ],
    ),
    (
        "role-models",
        "🌟",
        "deep",
        "Role models",
        "롤모델",
        "존경하는 사람과 이유.",
        [
            "Who do you look up to?",
            "What have you learned from them?",
            "Do celebrities make good role models?",
        ],
    ),
    (
        "future-tech",
        "🔮",
        "tech",
        "Life in 2050",
        "2050년의 삶",
        "미래 예측과 기대.",
        [
            "What will daily life look like in 2050?",
            "Flying cars or robot chefs?",
            "Are you optimistic about the future?",
        ],
    ),
    (
        "volunteering",
        "🙌",
        "society",
        "Helping others",
        "봉사와 나눔",
        "봉사 경험과 기부.",
        [
            "Have you ever volunteered?",
            "What causes matter to you?",
            "Is kindness contagious?",
        ],
    ),
    (
        "superpower",
        "🦸",
        "fun",
        "If you had a superpower",
        "초능력이 생긴다면",
        "가볍고 재밌는 상상 대화.",
        [
            "What superpower would you pick?",
            "How would you use it?",
            "Would you tell anyone?",
        ],
    ),
    (
        "desert-island",
        "🏝️",
        "fun",
        "Desert island picks",
        "무인도에 가져갈 것",
        "세 가지만 고른다면?",
        [
            "Three things for a desert island?",
            "Which person would you bring?",
            "How long would you survive?",
        ],
    ),
    (
        "time-travel",
        "⏳",
        "fun",
        "Time travel",
        "시간 여행",
        "과거나 미래로 간다면.",
        ["Past or future?", "Which year and why?", "Would you change anything?"],
    ),
    (
        "lottery",
        "🎰",
        "fun",
        "Winning the lottery",
        "복권 당첨",
        "큰돈이 생기면 할 일.",
        [
            "What would you do with a million dollars?",
            "Would you keep working?",
            "Who would you tell?",
        ],
    ),
    (
        "pet-peeves",
        "😤",
        "fun",
        "Pet peeves",
        "사소한 짜증",
        "은근히 거슬리는 것들.",
        [
            "What's a small thing that annoys you?",
            "Loud chewing or slow walkers?",
            "How do you react?",
        ],
    ),
    (
        "weekend-trip",
        "🚗",
        "travel",
        "Planning a weekend trip",
        "주말 여행 계획하기",
        "함께 여행 계획을 짜 보세요.",
        ["Where should we go this weekend?", "Train or car?", "What's the budget?"],
    ),
    (
        "restaurant-review",
        "⭐",
        "food",
        "Reviewing a restaurant",
        "맛집 리뷰",
        "최근 간 식당을 묘사하고 평가.",
        [
            "Tell me about the last restaurant you went to.",
            "How was the service?",
            "Would you go back?",
        ],
    ),
    (
        "health-habits",
        "🥗",
        "health",
        "Healthy eating",
        "건강한 식습관",
        "다이어트, 야식, 간헐적 단식.",
        [
            "Do you try to eat healthy?",
            "What's your weakness?",
            "Have you tried any diets?",
        ],
    ),
    (
        "apartment-life",
        "🏢",
        "society",
        "Apartment life",
        "아파트 생활",
        "층간소음, 이웃, 편의성.",
        ["Do you know your neighbors?", "Is noise a problem?", "House or apartment?"],
    ),
    (
        "online-dating",
        "💬",
        "society",
        "Meeting people online",
        "온라인으로 사람 만나기",
        "온라인 커뮤니티와 만남 문화.",
        ["Have you made friends online?", "Is it safe?", "How has dating changed?"],
    ),
    (
        "procrastination",
        "🐢",
        "study",
        "Procrastination",
        "미루는 습관",
        "왜 미루는지와 극복법.",
        [
            "What do you procrastinate on?",
            "What's your trick to start?",
            "Is procrastination always bad?",
        ],
    ),
]

CATEGORY_LABELS = {
    "daily": "일상",
    "food": "음식",
    "travel": "여행",
    "life": "라이프",
    "health": "건강",
    "work": "직장",
    "study": "공부",
    "culture": "문화",
    "tech": "테크",
    "society": "사회",
    "deep": "생각",
    "fun": "재미",
}

TOPIC_BANK = [
    {
        "id": t[0],
        "emoji": t[1],
        "category": t[2],
        "category_label": CATEGORY_LABELS[t[2]],
        "title": t[3],
        "title_ko": t[4],
        "description_ko": t[5],
        "questions": t[6],
    }
    for t in _RAW
]
TOPIC_MAP = {t["id"]: t for t in TOPIC_BANK}

# 롤플레이 시나리오: AI 가 특정 역할을 맡고 사용자는 상황을 해결한다
SCENARIOS = [
    {
        "id": "airport-checkin",
        "emoji": "🛫",
        "title": "Airport check-in",
        "title_ko": "공항 체크인",
        "description_ko": "짐 부치기, 좌석 요청, 지연 문의.",
        "ai_role": "an airline check-in agent",
        "user_role": "a traveler checking in for an international flight",
        "situation": "The flight is slightly overbooked; the traveler wants a window seat and asks about baggage allowance.",
        "level": "beginner",
    },
    {
        "id": "hotel-problem",
        "emoji": "🏨",
        "title": "Hotel room problem",
        "title_ko": "호텔 컴플레인",
        "description_ko": "방에 문제가 있어 프런트에 전화하기.",
        "ai_role": "a hotel front-desk receptionist",
        "user_role": "a guest whose room has a broken air conditioner and noisy neighbors",
        "situation": "It's late at night. The guest wants a solution: a fix, a room change, or compensation.",
        "level": "beginner",
    },
    {
        "id": "restaurant-order",
        "emoji": "🍽️",
        "title": "Ordering at a restaurant",
        "title_ko": "레스토랑 주문",
        "description_ko": "메뉴 질문, 알레르기, 추천 받기, 계산.",
        "ai_role": "a friendly server at a busy bistro",
        "user_role": "a customer ordering dinner",
        "situation": "The customer has a nut allergy and wants a recommendation; later something is wrong with the bill.",
        "level": "beginner",
    },
    {
        "id": "doctor-visit",
        "emoji": "🩺",
        "title": "Telehealth appointment",
        "title_ko": "병원 전화 진료",
        "description_ko": "증상 설명하고 조언 듣기.",
        "ai_role": "a general practitioner",
        "user_role": "a patient with a sore throat, mild fever and a cough for three days",
        "situation": "The doctor asks questions to understand symptoms and gives general advice and next steps.",
        "level": "intermediate",
    },
    {
        "id": "job-interview",
        "emoji": "💼",
        "title": "Job interview",
        "title_ko": "영어 면접",
        "description_ko": "자기소개, 경험, 강점, 질문하기.",
        "ai_role": "a hiring manager",
        "user_role": "a candidate for a role they are interested in (ask them what role)",
        "situation": "A 10-minute first-round phone interview with follow-up questions.",
        "level": "advanced",
    },
    {
        "id": "customer-service",
        "emoji": "📦",
        "title": "Late delivery complaint",
        "title_ko": "배송 지연 컴플레인",
        "description_ko": "주문 상태 확인, 환불 요청.",
        "ai_role": "a customer service representative for an online store",
        "user_role": "a customer whose order is a week late",
        "situation": "The customer wants either fast redelivery or a refund; the rep must verify details and offer options.",
        "level": "intermediate",
    },
    {
        "id": "apartment-viewing",
        "emoji": "🔑",
        "title": "Renting an apartment",
        "title_ko": "집 구하기",
        "description_ko": "월세, 보증금, 계약 조건 협상.",
        "ai_role": "a real-estate agent",
        "user_role": "someone looking for a one-bedroom apartment near downtown",
        "situation": "Discuss budget, location, lease length, deposit, and negotiate a small discount.",
        "level": "intermediate",
    },
    {
        "id": "bank-card",
        "emoji": "💳",
        "title": "Lost credit card",
        "title_ko": "카드 분실 신고",
        "description_ko": "카드 정지, 재발급, 의심 거래.",
        "ai_role": "a bank call-center agent",
        "user_role": "a customer who lost their credit card abroad",
        "situation": "Verify identity, block the card, check suspicious transactions, arrange a replacement.",
        "level": "intermediate",
    },
    {
        "id": "small-talk-party",
        "emoji": "🥂",
        "title": "Small talk at a party",
        "title_ko": "파티에서 스몰토크",
        "description_ko": "처음 만난 사람과 자연스럽게 대화 이어가기.",
        "ai_role": "a friendly stranger at a friend's housewarming party",
        "user_role": "a guest who knows almost nobody",
        "situation": "Break the ice, find common interests, exchange contacts naturally.",
        "level": "beginner",
    },
    {
        "id": "meeting-update",
        "emoji": "📊",
        "title": "Project status call",
        "title_ko": "프로젝트 진행 보고",
        "description_ko": "진행 상황, 이슈, 일정 조율.",
        "ai_role": "a project manager",
        "user_role": "a team member giving a weekly update",
        "situation": "One task is delayed; explain why, propose a new timeline and ask for resources.",
        "level": "advanced",
    },
    {
        "id": "directions",
        "emoji": "🧭",
        "title": "Asking for directions",
        "title_ko": "길 묻기",
        "description_ko": "낯선 도시에서 길과 교통 묻기.",
        "ai_role": "a helpful local on the street",
        "user_role": "a lost tourist trying to reach the central station",
        "situation": "Phone battery is nearly dead; get clear walking or subway directions and a nearby cafe recommendation.",
        "level": "beginner",
    },
    {
        "id": "return-item",
        "emoji": "🧾",
        "title": "Returning a product",
        "title_ko": "물건 환불/교환",
        "description_ko": "영수증 없이 교환 요청하기.",
        "ai_role": "a store clerk at a clothing shop",
        "user_role": "a customer returning a jacket that doesn't fit, without a receipt",
        "situation": "Store policy is strict; negotiate an exchange or store credit politely.",
        "level": "beginner",
    },
    {
        "id": "coffee-chat",
        "emoji": "☕",
        "title": "Networking coffee chat",
        "title_ko": "커피챗 (네트워킹)",
        "description_ko": "선배에게 커리어 조언 구하기.",
        "ai_role": "a senior professional in the learner's field (ask which field)",
        "user_role": "a junior asking for career advice",
        "situation": "15-minute informal call: background, advice, and asking for an introduction.",
        "level": "advanced",
    },
    {
        "id": "roommate-issue",
        "emoji": "🧹",
        "title": "Roommate disagreement",
        "title_ko": "룸메이트와 갈등 해결",
        "description_ko": "청소, 소음, 공과금 분담 이야기.",
        "ai_role": "a roommate who has been a bit messy lately",
        "user_role": "a roommate raising the issue kindly",
        "situation": "Find a fair cleaning schedule and split bills without hurting the friendship.",
        "level": "intermediate",
    },
    {
        "id": "emergency-call",
        "emoji": "🚑",
        "title": "Reporting an emergency",
        "title_ko": "긴급 상황 신고",
        "description_ko": "상황, 위치, 상태를 침착하게 설명.",
        "ai_role": "an emergency dispatcher",
        "user_role": "a witness reporting a minor traffic accident",
        "situation": "Give location, describe injuries, follow instructions until help arrives.",
        "level": "intermediate",
    },
    {
        "id": "presentation-qa",
        "emoji": "🎤",
        "title": "Presentation Q&A",
        "title_ko": "발표 후 질의응답",
        "description_ko": "발표 내용에 대한 질문에 답하기.",
        "ai_role": "an audience member asking questions after the learner's presentation (ask what the talk was about)",
        "user_role": "a presenter handling Q&A",
        "situation": "Some questions are tough or off-topic; answer clearly and buy time politely when needed.",
        "level": "advanced",
    },
]
SCENARIO_MAP = {s["id"]: s for s in SCENARIOS}


def daily_topics(date_str: str | None = None, n: int = 6) -> list[dict]:
    """날짜 기반 결정적 셔플 → 매일 다른 n개. 카테고리가 겹치지 않도록 고른다."""
    date_str = date_str or today_kst()
    seed = int(hashlib.sha256(date_str.encode()).hexdigest(), 16)
    items = list(TOPIC_BANK)
    # Fisher-Yates with LCG from seed
    x = seed
    for i in range(len(items) - 1, 0, -1):
        x = (x * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        j = x % (i + 1)
        items[i], items[j] = items[j], items[i]
    picked, seen_cat = [], set()
    for t in items:
        if t["category"] in seen_cat:
            continue
        picked.append(t)
        seen_cat.add(t["category"])
        if len(picked) >= n:
            break
    for t in items:
        if len(picked) >= n:
            break
        if t not in picked:
            picked.append(t)
    return picked


def daily_scenario(date_str: str | None = None) -> dict:
    date_str = date_str or today_kst()
    seed = int(hashlib.sha256(("scn" + date_str).encode()).hexdigest(), 16)
    return SCENARIOS[seed % len(SCENARIOS)]
